name: Universal Research
on:
  workflow_dispatch:
jobs:
  research:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix-shell -p curl --run 'curl -s ifconfig.me > ip.txt'
      - run: nix-shell -p coreutils --run 'echo "Research completed" > status.txt'
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            ip.txt
            status.txt